name = "Quine"
version = "0.1.0"
defaultTargets = ["Quine"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.28.0-rc1"

[[require]]
name = "Dress"
git = "https://github.com/e-vergo/Dress.git"
rev = "main"

[[lean_lib]]
name = "Quine"

[[lean_exe]]
name = "quine"
root = "Quine"
